version: '3.7'
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php.dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - unity

  mysql:
    restart: on-failure
    image: 'mysql:8.0.19'
    ports:
      - ${DB_PORT-3306}:3306
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: unity
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - unity

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx.dockerfile
    volumes:
      - .:/var/www
    ports:
      - ${NGINX_PORT-80}:80
    networks:
      - unity

networks:
  unity:
